#!/bin/bash

echo 74 > /sys/class/gpio/export
sleep 0.3
echo out > /sys/class/gpio/gpio74/direction
sleep 0.3
echo 0 > /sys/class/gpio/gpio74/value
sleep 0.3
echo 1 > /sys/class/gpio/gpio74/value
sleep 2
echo 0 > /sys/class/gpio/gpio74/value
sleep 0.3